### ISSUE TITLE
Struggling to understand docs on how to use this module

### ISSUE THREAD

**Issue by loganmarchione** [foo-dogsquared/hugo-mod-simple-icons#3]
Hi, 

I'd like to use Simple Icons in my site, but I'm not understanding Hugo modules. Below is my `config.yaml` file.

```
module:
  hugoVersion:
    extended: true
  imports:
    - path: github.com/adityatelange/hugo-PaperMod
    - path: github.com/foo-dogsquared/hugo-mod-simple-icons 
```
I then run these commands:
```
hugo mod init github.com/loganmarchione/loganmarchione.com
hugo mod get
hugo server
```

I can serve the site, and my theme works, but I'm not seeing anything in my assets folder. I was expecting to see some SVG files inside `assets/svg/simple-icons`. Is this not correct?

```
% tree assets
assets
└── css
    └── extended
        └── pre.css
```
